development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: counting_company_production

test:
  adapter: async

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: counting_company_production
